### ISSUE TITLE
Error DateTime type hint

### ISSUE THREAD

**Issue by stephanekp** [amazon-php/sp-api-sdk#114]
I think there is an error regarding the way some parameters for the functions have not the good types.

The error I have found is in the financial SDK part in the class  https://github.com/amazon-php/sp-api-sdk/blob/3.x/src/AmazonPHP/SellingPartner/Api/DefaultApi/FinancesSDK.php

If we check the api https://raw.githubusercontent.com/amzn/selling-partner-api-models/main/models/finances-api-model/financesV0.json
especially the line regardring the method "/finances/v0/financialEvents

One of the parameters is PostedAfter
```
      { "name": "PostedAfter",
      "in": "query",
      "description": "A date used for selecting financial events posted after (or at) a specified time. The date-time must be no later than two minutes before the request was submitted, in ISO 8601 date time format.",
      "required": false,
      "type": "string",
      "format": "date-time"}
```

The method autogenerated becomes

```
/**
     * Operation listFinancialEvents.
     *
     * @param AccessToken $accessToken
     * @param int $max_results_per_page The maximum number of results to return per page. (optional, default to 100)
     * @param \DateTime $posted_after A date used for selecting financial events posted after (or at) a specified time. The date-time must be no later than two minutes before the request was submitted, in ISO 8601 date time format. (optional)
     * @param \DateTime $posted_before A date used for selecting financial events posted before (but not at) a specified time. The date-time must be later than PostedAfter and no later than two minutes before the request was submitted, in ISO 8601 date time format. If PostedAfter and PostedBefore are more than 180 days apart, no financial events are returned. You must specify the PostedAfter parameter if you specify the PostedBefore parameter. Default: Now minus two minutes. (optional)
     * @param string $next_token A string token returned in the response of your previous request. (optional)
     *
     * @throws \AmazonPHP\SellingPartner\Exception\ApiException on non-2xx response
     * @throws \AmazonPHP\SellingPartner\Exception\InvalidArgumentException
     */
    public function listFinancialEvents(AccessToken $accessToken, string $region, int $max_results_per_page = 100, \DateTime $posted_after = null, \DateTime $posted_before = null, string $next_token = null) : \AmazonPHP\SellingPartner\Model\Finances\ListFinancialEventsResponse
    { 
 
```

The request that will be geberated won't transform as a parameter of the request to fit with the ISO 8601 requirements. https://github.com/amazon-php/sp-api-sdk/blob/06a6860c91cfc0f981c6ffb262f331c0f421b34a/src/AmazonPHP/SellingPartner/Api/DefaultApi/FinancesSDK.php#L420

I think that all of this DateTime parameters should hint as a string.

**Comment by norberttech** [comment]
Thanks for the detailed explanation @stephanekp 
https://github.com/amazon-php/sp-api-sdk/releases/tag/3.0.4 should resolve the issue you found!

**Comment by stephanekp** [comment]
Thnaks you for your quick fix.
And your great job for the community



Stéphane Lanjard

technical lead


KP France 12 rue des Mésanges, Lot 20 64200 Biarritz

(+33) 06 08 84 59 56

www.kpsport.com<http://www.kpsport.com/>



[cid:b8670596-0c4d-4b82-9f31-298e07d39bb7]


________________________________
De : Norbert Orzechowicz ***@***.***>
Envoyé : vendredi 7 janvier 2022 11:29
À : amazon-php/sp-api-sdk ***@***.***>
Cc : Stephane Lanjard ***@***.***>; Mention ***@***.***>
Objet : Re: [amazon-php/sp-api-sdk] Error DateTime type hint (Issue #114)


Thanks for the detailed explanation @stephanekp<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstephanekp&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uhkJ1vwOeC6ZalJqNTPMDHY%2BcBW0Qz%2FWGGb2ezaZUgU%3D&reserved=0>
https://github.com/amazon-php/sp-api-sdk/releases/tag/3.0.4<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famazon-php%2Fsp-api-sdk%2Freleases%2Ftag%2F3.0.4&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UaSTVHOl8x7jZzOy3ao%2BtYXsPw1VDuqv6dMGBP6r7u8%3D&reserved=0> should resolve the issue you found!

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famazon-php%2Fsp-api-sdk%2Fissues%2F114%23issuecomment-1007301712&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UsfS10BTrw4yC5BWo60AkNluFc9IVNZQMmvbq79014E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUWO7D7MMA2BOTQBC56ZKB3UU257ZANCNFSM5LM2XYAA&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R3xhAfCIehs%2FgroydyTK4%2FkSs8vI45o4zWJUepXInjM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8tHwDsHDF9NPoh%2Bemc%2FhvZDpp8pq4Bsa%2Fp%2BCnsS3bYs%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstephane.lanjard%40kpsport.com%7C29f06d143f944f3ac41708d9d1c88f5e%7Cabaa152e34684c8bb61a9d2daf53cced%7C0%7C0%7C637771481589275957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0IVPgZhxQKz%2BXekH9EwV%2F6sA8i61e%2FGKEKubnkUuRYE%3D&reserved=0>.
