### ISSUE TITLE
VendorSDK and Purchase Orders

### ISSUE THREAD

**Issue by charliebdn** [amazon-php/sp-api-sdk#120]
Hi everyone,

I've recently installed your SDK. It's amazing and very useful, I just can't imagine how much time I would have spent generating and adapting SP API via Swagger-codegen.

There is something I just saw when trying to use the Vendors OrderSDK.
https://github.com/amazon-php/sp-api-sdk/blob/ff8ea7e572f1a8a32a451784f4c688b267e8bf75/src/AmazonPHP/SellingPartner/VendorSDK.php#L21

Shouldn't this be a property of class OrdersSDK?

Thanks in advance.

**Comment by norberttech** [comment]
Hey @charliebdn 
so the current approach of this library is to group SDK's just like Amazon grouped their [models](https://github.com/amzn/selling-partner-api-models/tree/main/models) .
So you can expect to see SDK's like in the following image:  

`VendorSDK` referenced by you is a Facade to all Vendor API SDK's 
![image](https://user-images.githubusercontent.com/1921950/149489811-14a9a008-8e61-4159-82a5-10f36f843a0a.png)

Honestly, I don't know why they decided to organize Vendor API Endpoints this way, I would personally do it a bit differently. 

Does this answer your question?

**Comment by charliebdn** [comment]
Yes, thanks for your response! @norberttech
