### ISSUE TITLE
Catalog Item image variant validation error

### ISSUE THREAD

**Issue by isalmin** [amazon-php/sp-api-sdk#156]
InvalidArgumentException: Invalid value 'PT09' for 'variant', must be one of 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT08', 'SWCH'

/app/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/CatalogItem/ItemImage.php:315

Example ASIN: B0000CF98Q

**Comment by norberttech** [comment]
Hey, it seems that PT09 is not expected in the [mode](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2020-12-01.json#L1157-L1218). 

Could you please open an issue in this [amzn/selling-partner-api-models](https://github.com/amzn/selling-partner-api-models) repository?

**Comment by norberttech** [comment]
https://github.com/amazon-php/sp-api-sdk/pull/192 - should temporarily resolve this issue.

**Comment by norberttech** [comment]
resolved by https://github.com/amazon-php/sp-api-sdk/pull/199 and https://github.com/amazon-php/sp-api-sdk/pull/192
