### ISSUE TITLE
Error 403 - Error connecting to the API --> AccessDeniedException

### ISSUE THREAD

**Issue by younesbakkas** [amazon-php/sp-api-sdk#170]
Hello,

I'm a new user of Amazon SP-API, and I can't execute any API function because of a 403 error - AccessDeniedException

**Example while trying to execute the example given in README.md (getCatalogItem)**
`[403] Error connecting to the API (https://sellingpartnerapi-eu.amazon.com/catalog/2020-12-01/items/A13V1IB3VIYZZH?marketplaceIds=B00SG7KRRU)"`

Access token ($accessToken) is correctly returned by  exchangeRefreshToken('REFRESH TOKEN') function

I have created a new user in AWS with these policy given in the README.md, but also with these following policies : 

- AWSMarketplaceFullAccess
- AdministratorAccess
- AWSPrivateMarketplaceAdminFullAccess
- AdministratorAccess-Amplify
- AWSMarketplaceSellerFullAccess

In the Amazon Seller, I've created an application and I've add my AWS user with IAM identifier

I've also tryied to authorise new developer in the SellerCentral page, but I've this error : **MD9000**
![Sans titre2](https://user-images.githubusercontent.com/97090864/169280069-86ba7ca7-613c-479d-a3cb-84ea655c0175.png)

I don't know what I've missed ?????
Thanks for your help

![Sans titre](https://user-images.githubusercontent.com/97090864/169278922-cca907fe-af02-48fb-83b6-f41eb69750b8.png)

**Comment by jasonhebert** [comment]
From the URL it looks like you have the ASIN and MarketplaceId backwards.
It looks like the url has the ASIN in the marketplaceIds parameter and the
MarketplaceID in the ASIN spot of the URL. Check that you are passing them
correctly.
--

Jason P. Hebert
T 228.206.5309 | E h ***@***.***>
***@***.***

**Comment by younesbakkas** [comment]
**OK thank you** 👍👍👍👍👍 
It seems that the example given in README.md is wrong :'(

![Sans titre](https://user-images.githubusercontent.com/97090864/169334642-b1ca23fb-d0f0-4f5b-94b0-d4cb6f1b3045.png)

**Comment by jasonhebert** [comment]
PR submitted with correction: https://github.com/amazon-php/sp-api-sdk/pull/171

**Comment by norberttech** [comment]
Merged, thank you guys!
