### ISSUE TITLE
[Listings Items - patchListingsItem] - InvalidInput : Request has missing or invalid parameters and cannot be parsed

### ISSUE THREAD

**Issue by younesbakkas** [amazon-php/sp-api-sdk#172]
Hello !

Calling patchListingsItem() function return an error : **_InvalidInput : Request has missing or invalid parameters and cannot be parsed_**

Maybe the body is not correctly implemented
I noticed that json_encode() adds "\" in the "patches" property, which is not present in the exemple given in this documentation : _**[https://spapi.cyou/en/use-case/listings-items-api-use-case-guide_2021-08-01.html#step-1-submit-listings-item-patch-request]**_

I've tried to delete them but I've the same issue.

You can see attachment for more detail.
**[patchListingsItem.docx](https://github.com/amazon-php/sp-api-sdk/files/8738149/patchListingsItem.docx)**

Thank you :)

**Comment by jasonhebert** [comment]
Have you ensured that the sellerId, sku, and marketplaceIds properties are correct and valid values AND that the body of the request has valid values as well? The body is formatted properly as far as I can tell but the values could possibly be incorrect for your application.

**Comment by younesbakkas** [comment]
About SellerID, SKU and MarketplaceID, they are correct, I think
About the body, its structure seems OK but I don't know if I need to add some required informations. I didn't find any documentation about what this body should contain :(

Maybe if I find a postman package which is fully functionnal, I coul'd try it and check if my code is OK (I tried a lot but no one works)


Thank you :)

**Comment by younesbakkas** [comment]
OK, my bad
In the body, the "patches" part needed to be encapsulated in another array.

![image](https://user-images.githubusercontent.com/97090864/169771269-74d75e9d-a2fe-4809-a8b1-85569e9776ec.png)

Thank you !

**Comment by norberttech** [comment]
I'm glad that you managed to resolve this issue. 
Thanks again @jasonhebert for your help!
I'm closing this issue
