### ISSUE TITLE
FBAInventorySDK getInventorySummaries method not serializing boolean $details param as string

### ISSUE THREAD

**Issue by jasonhebert** [amazon-php/sp-api-sdk#187]
The FBAInventorySDK getInventorySummaries method has an optional boolean parameter `$details` with a default boolean `false` value. When serializing to string value for use in the API call the value becomes `0` or `1`. The API call expects string values of `true` and `false`.

This following incorrect URI is created with the library:
```
https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=1&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=ATVPDKIKX0DER
```

The following is the expected URI:
```
https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=ATVPDKIKX0DER
```

The following response body is returned with a 400 error code:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

While this is not entirely helpful I was able to determine the cause thru trial and error, manually creating the variations on the URI.

I would suspect that the same is true of any calls that have boolean values as params.

**Comment by jasonhebert** [comment]
Upon further investigation I think the `api.mustache` template lines 287 to 297 could be updated to the following:

```
{{^isExplode}}
if (is_array(${{paramName}})) {
    ${{paramName}} = ObjectSerializer::serializeCollection(${{paramName}}, '{{#style}}{{style}}{{/style}}{{^style}}{{#collectionFormat}}{{collectionFormat}}{{/collectionFormat}}{{/style}}', true);
}

if (${{paramName}} !== null) {
    $queryParams['{{baseName}}'] = ObjectSerializer::toString(${{paramName}});
}
{{/isExplode}}
```

**Comment by norberttech** [comment]
What you described (SDK expects `boolean`, amazon returns `"0"` or `"1"`) sounds more like something we could try to solve in [ObjectSerializer](https://github.com/amazon-php/sp-api-sdk/blob/4.x/src/AmazonPHP/SellingPartner/ObjectSerializer.php#L318-L321)

**Comment by jasonhebert** [comment]
It's the other way around. This is in the request. Amazon expects boolean as string such as `true` and `false` but the boolean properties get cast to string as `1` and `0` in the SDK when building the URI query string. The boolean params never go thru the `ObjectSerializer`. This is why I suggested changing the template to send them thru the `ObjectSerializer::toString()` method.

**Comment by norberttech** [comment]
oh now I see, yeah, that should solve the problem 👍

**Comment by jasonhebert** [comment]
I could update the mustache template but cannot run the build to regenerate the resources so I shall leave that up to you when you have the time.

Thanks...

**Comment by norberttech** [comment]
I think this should do the job https://github.com/amazon-php/sp-api-sdk/pull/188 
Additionally I managed to fixed code regeneration, you can do it through executing `composer generate` but make sure to have docker launched. 

Could you check if proposed solution worked before I tag new release?

**Comment by jasonhebert** [comment]
I can check at some point over the weekend and let you know but the re-generated code looks good.

**Comment by jasonhebert** [comment]
Works like a charm for the issue I was having. The `bool` values are now string `true` and `false` on the URI and no-longer fails.

**Comment by norberttech** [comment]
In that case I believe we can consider this one as resolved. I will tag next version once I handle https://github.com/amazon-php/sp-api-sdk/issues/186
