### ISSUE TITLE
SP-API getPackageTrackingDetails does not respond correctly when an unknown event code is responded. Part 2.

### ISSUE THREAD

**Issue by Tetsuya-Takiguchi** [amazon-php/sp-api-sdk#195]
https://github.com/norberttech/sp-api-sdk/blob/3e0421ca3b6934d5b3e5284e6613c6123ee36c87/src/AmazonPHP/SellingPartner/ObjectSerializer.php#L67

The same response to #192 is needed at the above location.

**Comment by norberttech** [comment]
Thanks, @Tetsuya-Takiguchi I don't have a reliable way to reproduce those issues locally, could you please open a PR? 
Another solution is to wait for amazon to correct the model definitions.

**Comment by Tetsuya-Takiguchi** [comment]
Hi, @norberttech 
Thank you.
Since you suggested it, I have modified the module on my end to push the modified module, but I get an error message `Permission to amazon-php/sp-api-sdk.git denied`.
Are there any rules for pushing to the repository?

**Comment by norberttech** [comment]
As a contributor, you are not allowed to push directly into the repository. 
Instead, you need to fork the project, push your changes to your fork and then open a pull request.

[more about working with forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks)

**Comment by Tetsuya-Takiguchi** [comment]
Thank you for your guidance.
I will now create a PR using the method you have indicated.
As for this issue, should I delete it?

**Comment by norberttech** [comment]
resolved by https://github.com/amazon-php/sp-api-sdk/pull/199
