### ISSUE TITLE
Seems like grantless operations does not work

### ISSUE THREAD

**Issue by dimaraduk91** [amazon-php/sp-api-sdk#197]
Hi, I'm not able to create a destination for notifications

`
$notifications = $this->sdk->notifications();
$accessToken = $this->sdk->oAuth()->clientCredentials('sellingpartnerapi::notifications');

$destination = $notifications->createDestination($accessToken, $region, new CreateDestinationRequest([
    'resource_specification' => new DestinationResourceSpecification([
        'sqs' => new SqsResource([
            'arn' => 'arn:aws:sqs:region:id...'
        ]),
    ]),
    'name' => 'Test name',
]));`

Response:
In NotificationsSDK.php line 149:                                                                                                             
  [409] Error connecting to the API (https://sellingpartnerapi-eu.amazon.com/notifications/v1/destinations) 

Any thoughts? What am I doing in a wrong way?

**Comment by norberttech** [comment]
There should be more details in the exceptions (or logs if you have logger configured). 
409 status code means `Maximum number of attempts has been exceeded.`, but it's probably something different however you need to provide more data. 

Does other API calls work for you?

**Comment by norberttech** [comment]
I'm closing this one since there are not enough details provided even to figure out if that's API or credentials issue. 
Feel free to create a new issue or ping me to open this one in case it's still not working as you would expect.
