### ISSUE TITLE
Uncaught Exception: Cannot Destructure Property 'packageJson'

### ISSUE THREAD

**Issue by skaraudio** [amazon-php/sp-api-sdk#232]
Hello,

Please advise, I have not had any issue running this on serverless until today.

Did something change? Nothing is forseeably wrong on my end, and have hundreds of Lambda functions.

![image](https://user-images.githubusercontent.com/15099697/185009505-13cdec67-7372-427f-a8c9-de473857fc64.png)

**Comment by norberttech** [comment]
Hey, it does not seems to be related to the library itself, there is even not packageJson property in the entire project from what I remember, it might be something with the serverless runner itself.
