### ISSUE TITLE
Catalog Item API version 2022-04-01 for php 7.4

### ISSUE THREAD

**Issue by haffoudhi** [amazon-php/sp-api-sdk#256]
Hey, 
can we expect an update for php 7.4. Or we just have to upgrade to php 8 instead?

**Comment by norberttech** [comment]
hey, sorry I do not have any plans at this point to support php 7.4 as it's getting end of life soon anyway. 
Migration to 8.1 is not on your radar?

**Comment by haffoudhi** [comment]
Sure, I have to. I like your sdk, so I will try the upgrade asap.

I noticed some bug in version 5.x.dev in /amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/CatalogItem/Item.php

public function setAttributes(?object $attributes) : self

I m getting an error. it should be ?array not ?object.
