### ISSUE TITLE
Problem with jsonSerialize function

### ISSUE THREAD

**Issue by st-pimentel** [amazon-php/sp-api-sdk#262]
Using the OrdersSDK the function `jsonSerialize`, sometimes have an exception.

`"AmazonPHP\SellingPartner\Model\Orders\Address::getName(): Return value must be of type string, null returned"`

The strange part is, if I try to collect the name using `getOrderAddress`, `getShippingAddress` and finally the `getName`, I 
retrieve the name without any problem.

Debugging I found that the `$this->container` seems to be empty for most of attributes.

I tried both version 4 and 5.

**Comment by xiaoguo0426** [comment]
the same problem with me

**Comment by norberttech** [comment]
Hey, could you check if you using RDT to access orders api endpoint?

**Comment by st-pimentel** [comment]
What you mean with RDT ?
And I can access the Orders, the Orders details like Address, Items, Buyer, all it is fine.
Only the function jsonSerialize that outputs this error.

**Comment by norberttech** [comment]
if you are not using RDT, this is exactly how the orders api should behave.
https://github.com/amazon-php/sp-api-sdk/discussions/202

**Comment by st-pimentel** [comment]
Yes, following the example it work.
The strange thing was everything also worked without RDT, except the jsonSerialize, but the RDT seems to be the proper way to do the calls.

Thank you!
