### ISSUE TITLE
Miss Currency code EUR

### ISSUE THREAD

**Issue by stephanekp** [amazon-php/sp-api-sdk#274]
In the inbound shipment plan creation, the currency code EUR is missing AmazonPHP\SellingPartner\Model\FulfillmentInbound\Currency
"api" => "FulfillmentInbound",
"operation" => "createInboundShipmentPlan",

We got the response In ObjectSerializer.php line 347:
[InvalidArgumentException]                                                                                              
  Invalid value for enum '\AmazonPHP\SellingPartner\Model\FulfillmentInbound\CurrencyCode', must be one of: 'USD', 'GBP'

**Comment by norberttech** [comment]
https://github.com/amazon-php/sp-api-sdk/pull/331 this one should solve that problem, Amazon is terrible...
