### ISSUE TITLE
  Return value of AmazonPHP\SellingPartner\Model\Orders\Address::getName() must be of the type string, null returned

### ISSUE THREAD

**Issue by axsweet** [amazon-php/sp-api-sdk#328]
V: amazon-php/sp-api-sdk 4.0.12 Amazon Selling Partner API - PHP SDK
PHP V ~7.4

Some address is null so on jsonSerialize() I get this error... seems the data has a null and wants a string.

   TypeError

  Return value of AmazonPHP\SellingPartner\Model\Orders\Address::getName() must be of the type string, null returned

  at vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/Orders/Address.php:282
    278▕      * Gets name.
    279▕      */
    280▕     public function getName() : string
    281▕     {
  ➜ 282▕         return $this->container['name'];
    283▕     }
    284▕
    285▕     /**
    286▕      * Sets name.

      +6 vendor frames
  7   app/Console/Commands/AmazonCommands.php:660
      AmazonPHP\SellingPartner\Model\Orders\GetOrdersResponse::jsonSerialize()

**Comment by fawsan** [comment]
any answers on this ?

**Comment by axsweet** [comment]
I removed the strict types requirement on the ask file. 

But ultimately i beliehe i didn't have the approval (still waiting) to get the customer info. Found it funnny I can get 85% but need advanced approval for the name but. Anyway.

**Comment by stdmedoth** [comment]
I had the same problem.

I solved it by adding `?` in string return type on getName method from Address class

like this:
**before:** public function getName(): string
**after:** public function getName(): ?string

**Comment by axsweet** [comment]
Yeah i worked around it similarly by either A removing strict type
declaration or just the return type. except for the fact that the
information in the fields i wanted is infact coming as null because i need
extra permissions they wont grant it to be in dev vetting so we are working
on that. its frsutratig since we get that info now from MWS already.

A

**Comment by xiaoguo0426** [comment]
got the same error.

**Comment by bolner** [comment]
It's weird that there were tons of commits since the 2nd of February, but this issue is still not fixed:
https://github.com/amazon-php/sp-api-sdk/blob/cda85c7ad9f9fdcd537d4e25d532b022f33feaad/src/AmazonPHP/SellingPartner/Model/Orders/Address.php#L291

The API clearly returns NULL values for the address.name, so this library is not compatible with the Amazon SP-API.

**Comment by sergisolanellas** [comment]
Amazon will not fix this. The privacy of Amazon avoid to return the name, address, phone, etc...

**Comment by johncarlson21** [comment]
I think the privacy part is where you need to be approved for PII. 
I had no problem with our MWS app but now making this new one I think it needs to be approved.

**Comment by axsweet** [comment]
Yeah shoudlnt throw an error though should have error handling for
permissions. Would save devs time.

Anyway i only wanted to make the app for myself (my company) they
wont approve my dev access again. Dk why keep saying same reply have zero
idea.

**Comment by sergisolanellas** [comment]
> I think the privacy part is where you need to be approved for PII.
> I had no problem with our MWS app but now making this new one I think it needs to be approved.

Hi! Can you explain how it's possible to contact to Amazon to give the permission of receive all data of the orders? 

Thanks

**Comment by axsweet** [comment]
Apply for developer access

**Comment by jasonhebert** [comment]
This method returns string or null and shouldn't throw the error anymore.
