### ISSUE TITLE
incompatibility with symfony 6.2 exactly psr/log 3

### ISSUE THREAD

**Issue by romeolandry** [amazon-php/sp-api-sdk#330]
Hi hey,
I try to Test this sdk in with Symfony 6.2 application and composer return this error:

`composer require amazon-php/sp-api-sdk -w`

return 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires amazon-php/sp-api-sdk ^5.0 -> satisfiable by amazon-php/sp-api-sdk[5.0.0, 5.0.1].
    - amazon-php/sp-api-sdk[5.0.0, ..., 5.0.1] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but these were not loaded, likely because it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require amazon-php/sp-api-sdk:*" to figure out if any version is installable, or "composer require amazon-php/sp-api-sdk:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`
can you please change the composer.josn to allow `psr/log` version greated than 1.1? Please.

**Comment by norberttech** [comment]
Hey, feel free to open a PR that would add support for psr/log 3.0, it's on my todo list, but I can't promise any deadline so if it's something you need right now, feel free to contribute.

**Comment by norberttech** [comment]
https://github.com/amazon-php/sp-api-sdk/pull/342
