### ISSUE TITLE
pageSize needs to be nullable for getfeeds nextToken

### ISSUE THREAD

**Issue by naudelasticweb** [amazon-php/sp-api-sdk#336]
When retrieving the next page for the getFeeds endpoint we need to be able to put in a null pageSize

    {\n
      "errors": [\n
        {\n
          "code": "InvalidInput",\n
          "message": "NextToken cannot be specified with other input parameters",\n
          "details": "pageSize;"\n
        }\n
      ]\n
    }

on url `/feeds/2021-06-30/feeds?pageSize=10&nextToken=******`

**Comment by aik099** [comment]
@naudelasticweb , issue still present in both 5.x and 4.x branches. See https://github.com/amazon-php/sp-api-sdk/blob/4.x/src/AmazonPHP/SellingPartner/Api/FeedsApi/FeedsSDKInterface.php .

The same issue is also happening with reports api: #404 .

**Comment by aik099** [comment]
Actually closed by https://github.com/amazon-php/sp-api-sdk/pull/561 .
