### ISSUE TITLE
ListingsAPI putListingsItem returns invalid productType (INKJET_PRINTER_INK) (belgium)

### ISSUE THREAD

**Issue by PhenomEY** [amazon-php/sp-api-sdk#388]
Hey,
so far the putListingsItem Endpoint does not work for belgium because every productType is declined.
Is there any information on when the productTypes will be available for amazon belgium?

It works fine on every other marketplace

**Comment by jasonhebert** [comment]
This would be a question for Amazon if this has not been resolved
