### ISSUE TITLE
pageSize needs to be nullable for getReports nextToken

### ISSUE THREAD

**Issue by yosida001** [amazon-php/sp-api-sdk#404]
Hello,

I encountered a new issue while trying to use ReportsSDK::getReports() with the specified next_token parameter for GET /reports/2021-06-30/reports. Upon running the code, I received the following error from Amazon:

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "NextToken cannot be specified with other input parameters",
      "details": "pageSize;"
    }
  ]
}
```

After examining the source code, I noticed that pageSize is fixed as an integer type and does not allow null values, which prevents queries using next_token from functioning properly.

Reference:
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#get-reports2021-06-30reports

Thank you.

**Comment by aik099** [comment]
Getting the same issue in v4 version of the library.

**Comment by bolner** [comment]
If you guys don't want to change the interfaces, here is a quick fix.
Change this line:
https://github.com/amazon-php/sp-api-sdk/blob/1b44f8c445394cf35ad38dbb24e5f0a9027399ec/src/AmazonPHP/SellingPartner/Api/ReportsApi/ReportsSDK.php#L1733

To:
```
$queryParams = ['nextToken' => ObjectSerializer::toString($next_token)];
```

Meaning: If the next_token is set, then ignore all the other parameters.
Tested, works. But 45 seconds for 100 items is pretty slow.

**Comment by aik099** [comment]
Actually closed by https://github.com/amazon-php/sp-api-sdk/pull/561 .
