### ISSUE TITLE
Order shipmentConfirmation returns null

### ISSUE THREAD

**Issue by johncarlson21** [amazon-php/sp-api-sdk#438]
I am setting up our system to use the shipmentConfirmation call.
I've tested this using the sandbox, however on a successful call, it returns "null"

I think this should return some data such as the status code, error etc.
I do not think it should just fail, as we can then use this returned info to send emails with info to our system.

**Comment by jsanchez-inova** [comment]
must be of the type string, null 
PHP Fatal error:  Uncaught TypeError: Return value of AmazonPHP\SellingPartner\Model\Orders\Address::getName() must be of the type string, null returned in /home/jsanchez/www/domains/dev2.cron/bins/cron_scripts/amazon_mws_v2/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/Orders/Address.php:282

**Comment by jasonhebert** [comment]
This is an issue that should be taken up with the SP-API dev team at Amazon. You can submit an issue [here](https://github.com/amzn/selling-partner-api-models/issues). The OpenAPI spec has a null response returned from this API call and can be referenced here: [ordersV0.json line 2561](https://github.com/amzn/selling-partner-api-models/blob/9a138924f819741ebcd79c5d1e7f325595b73f76/models/orders-api-model/ordersV0.json#L2561)
