### ISSUE TITLE
must be of the type string, null 

### ISSUE THREAD

**Issue by jsanchez-inova** [amazon-php/sp-api-sdk#481]
Uncaught TypeError: Return value of AmazonPHP\SellingPartner\Model\Orders\Address::getName() must be of the type string, null returned in /home/jsanchez/www/domains/dev2.cron/bins/cron_scripts/amazon_mws_v2/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/Orders/Address.php:282

**Comment by jasonhebert** [comment]
This was fixed with version 5.0.7 where the `AmazonPHP/SellingPartner/Model/Orders/Address::getName()` method return type was made nullable.
