### ISSUE TITLE
Cannot pass null value to SellingPartner/Api/ReportsApi/ReportsSDK getReports() method page_size parameter

### ISSUE THREAD

**Issue by st0at** [amazon-php/sp-api-sdk#701]
When getting long list of reports you must use `nextToken` parameter to iterate via reports list pages:
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreports
`nextToken` parameter cannot be used with other parameters, or you will get 400 error:
```
code: "InvalidInput"
message: "NextToken cannot be specified with other input parameters"
details: "pageSize;"
```

But you cannot pass null value to `pageSize` parameter, because `getReportsRequest` method accepts only int type for `page_size` (SellingPartner/Api/ReportsApi/ReportsSDK line 1642). Possibility for null value must be added.

**Comment by jasonhebert** [comment]
Now fixed in version 6.2.0.
