### ISSUE TITLE
Role support roadmap

### ISSUE THREAD

**Issue by quazardous** [amazon-php/sp-api-sdk#80]
Is there a roadmap horizon for ARN role support ?

**Comment by norberttech** [comment]
Hey, yeah it's on my roadmap since first commit but I never can find enough time to work on it.
If anyone would like to pick it up, I'm happy to help. If not, I'll do my best to look into this next month

**Comment by norberttech** [comment]
https://github.com/amazon-php/sp-api-sdk/pull/104
